//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSONCreator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public string Chinese { get; set; }
        public string PinYin { get; set; }
        public string English { get; set; }
    }
}
